export * from './LoginRequest';
export * from './CreateAgencyRequest';
export * from './CreateUserRequest';
export * from './PlanRequest';
export * from './BenefitRequest';
export * from './DestinationRequest';
export * from './CreditRequest';
export * from './CreateQuoteClientDetailsRequest'
export * from './CreateQuoteKYCDetailsRequest'
export * from './UploadFileRequest'
export * from './SelectPlanRequest'
export * from './CreateQuoteKYCDetailsRequest'
export * from './AuthRequests'
export * from './PremiumRequest'
export * from './GetQuoteDocumentRequest'
export * from './SendToMail'